# Generated by Django 4.2.13 on 2024-11-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Cuarto')),
                ('capacidad', models.IntegerField(verbose_name='capacidad')),
                ('ocupacion', models.IntegerField(default=0, verbose_name='ocupacion')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='codigo')),
                ('direccion', models.CharField(max_length=250, verbose_name='direccion')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_identidad', models.CharField(max_length=11, unique=True, verbose_name='Carnet de Identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('facultad', models.CharField(max_length=100, verbose_name='Facultad')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('ano_academico', models.IntegerField(null=True, verbose_name='Año academico')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('cuarto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estudiantes', to='proceso_app.cuarto', verbose_name='cuarto')),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='codigo')),
                ('sexo', models.BooleanField(null=True, verbose_name='sexo')),
                ('sedeID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edificios', to='proceso_app.sede', verbose_name='sede')),
            ],
        ),
        migrations.CreateModel(
            name='Dormitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='codigo')),
                ('edificioID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dormitorios', to='proceso_app.edificio', verbose_name='edificio')),
            ],
        ),
        migrations.AddField(
            model_name='cuarto',
            name='dormitorioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuartos', to='proceso_app.dormitorio', verbose_name='dormitorio'),
        ),
    ]
