# Generated by Django 4.2.13 on 2024-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuarto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dormitorio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='id',
        ),
        migrations.AlterField(
            model_name='cuarto',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Cuarto'),
        ),
        migrations.AlterField(
            model_name='dormitorio',
            name='codigo',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='codigo',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carnet_identidad',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Carnet de Identidad'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='codigo',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='codigo'),
        ),
    ]
