# Generated by Django 4.2.13 on 2024-11-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso_app', '0002_dormitorio_descricpion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitorio',
            name='descricpion',
            field=models.CharField(max_length=250),
        ),
    ]
